local SelectText = require('cmp-kit.core.SelectText')

describe('cmp-kit.core', function()
  describe('SelectText', function()
    describe('.create', function()
      it('should return select text', function()
        assert.equals('#[test]', SelectText.create('#[test]'))
        assert.equals('#[[test]]', SelectText.create('#[[test]]'))
        assert.equals('insert', SelectText.create('insert()'))
        assert.equals('insert_text', SelectText.create('insert_text'))
        assert.equals('(insert)', SelectText.create('(insert))'))
        assert.equals('"true"', SelectText.create('"true"'))
      end)
    end)
  end)
end)
