local SelectText = require('cmp-kit.core.SelectText')

describe('cmp-kit.core', function()
  describe('SelectText', function()
    describe('.create', function()
      it('should return select text', function()
        assert.are.equal('#[test]', SelectText.create('#[test]', ''))
        assert.are.equal('#[[test]]', SelectText.create('#[[test]]', ''))
        assert.are.equal('insert', SelectText.create('insert()', ''))
        assert.are.equal('insert_text', SelectText.create('insert_text', ''))
        assert.are.equal('(insert)', SelectText.create('(insert))', ''))
        assert.are.equal('"true"', SelectText.create('"true"', ''))
        assert.are.equal('16', SelectText.create('16', ''))
        assert.are.equal('"repository', SelectText.create('"repository"', '"'))
      end)
    end)
  end)
end)
