local spec = require('cmp-kit.spec')
local Keymap = require('cmp-kit.kit.Vim.Keymap')
local TriggerContext = require('cmp-kit.core.TriggerContext')

describe('cmp-kit.completion', function()
  describe('TriggerContext', function()
    for _, mode in ipairs({ 'i', 'c' }) do
      describe(mode, function()
        describe('.create', function()
          it('should create trigger context', function()
            spec.reset()
            Keymap.spec(function()
              Keymap.send(mode == 'c' and ':' or 'i'):await()
              Keymap.send(Keymap.termcodes('foo+bar<Left><Left><Left>')):await()
              local trigger_context = TriggerContext.create({ trigger_character = '+' })
              assert.are.equal(mode, trigger_context.mode)
              assert.are.equal(4, trigger_context.character)
              assert.are.equal('foo+bar', trigger_context.text)
              assert.are.equal('foo+', trigger_context.text_before)
              assert.are.equal('foo+', trigger_context:get_query(1))
              assert.are.equal(false, trigger_context.force)
              assert.are.equal('+', trigger_context.before_character)
              Keymap.send('<Esc>'):await()
            end)
          end)
        end)
      end)
    end
  end)
end)
